name: talib_ilm
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: ^3.10.4


dependencies:
  path_provider: ^2.1.2 
  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: ^6.0.0
  flutter_pdfview: ^1.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/data/mutun_program.json
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/pdfs/mutun/bk_usul_thalatha.pdf

  fonts:
  - family: Amiri
    fonts:  
      - asset: assets/fonts/Amiri-Regular.ttf
      - asset: assets/fonts/Amiri-Bold.ttf

  - family: Vazirmatn
    fonts:
      - asset: assets/fonts/Vazirmatn-Regular.ttf
      - asset: assets/fonts/Vazirmatn-Bold.ttf

